MAILGUN_EMAIL_VALIDATION_API_PROTOCOL: "https://"
MAILGUN_EMAIL_VALIDATION_API_PATH: "api.mailgun.net/v2/address/validate"
MAILGUN_EMAIL_VALIDATION_PARAM_NAME: "address"
MAILGUN_EMAIL_VALIDATION_ID:
MAILGUN_EMAIL_VALIDATION_KEY:
development:
  SECRET_TOKEN:
  SENDGRID_USERNAME:
  SENDGRID_PASSWORD:
  DB_NAME:
  DB_USER:
  DB_PASSWORD:
test:
  SECRET_TOKEN:
  DB_NAME: 
  DB_USER:
  DB_PASSWORD:
production:
  SECRET_TOKEN:
