MAILGUN_EMAIL_VALIDATION_API_PROTOCOL: "https://"
MAILGUN_EMAIL_VALIDATION_API_PATH: "api.mailgun.net/v2/address/validate"
MAILGUN_EMAIL_VALIDATION_PARAM_NAME: "address"
MAILGUN_EMAIL_VALIDATION_ID:
MAILGUN_EMAIL_VALIDATION_KEY:
AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
DISPLAY_CONTACT_EMAIL:
FACEBOOK_URL: 
development:
  SECRET_TOKEN:
  SENDGRID_USERNAME:
  SENDGRID_PASSWORD:
  DB_NAME:
  DB_USER:
  DB_PASSWORD:
  AWS_BUCKET:
  ADMIN_EMAIL:
  ADMIN_PASSWORD:
  CONTACT_EMAIL:
test:
  SECRET_TOKEN:
  DB_NAME: 
  DB_USER:
  DB_PASSWORD:
  ADMIN_EMAIL:
  ADMIN_PASSWORD:
  CONTACT_EMAIL:
production:
  SECRET_TOKEN:
  AWS_BUCKET:
  CONTACT_EMAIL:
