default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: 5
  username: squarebean

development:
  <<: *default
  database: squarebean_development

test: &test
  <<: *default
  database: squarebean_test

cucumber:
  <<: *test
